// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvaslazcmocjditstuxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2YXNsYXpjbW9jamRpdHN0dXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzQ5MzIsImV4cCI6MjA3MTk1MDkzMn0.LlE4ylI-4prUzZOl5l0vNrxUC2COBOGez5hGYVCoRBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});